//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.roda_project.commons_ip2.mets_v1_12.beans;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import javax.xml.namespace.QName;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * seqType: Complex Type for Sequences of Files
 * The seq element should be used to link a div to a set of content files when those files should be played/displayed sequentially to deliver content to a user.  Individual <area> subelements within the seq element provide the links to the files or portions thereof.
 *
 *
 * <p>Java class for seqType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="seqType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded">
 *         <element name="area" type="{http://www.loc.gov/METS/}areaType" minOccurs="0"/>
 *         <element name="par" type="{http://www.loc.gov/METS/}parType" minOccurs="0"/>
 *       </choice>
 *       <attGroup ref="{http://www.loc.gov/METS/}ORDERLABELS"/>
 *       <attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       <anyAttribute processContents='lax' namespace='##other'/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "seqType", propOrder = {
    "areaOrPar"
})
public class SeqType {

  @XmlElements({
      @XmlElement(name = "area", type = AreaType.class),
      @XmlElement(name = "par", type = ParType.class)
  })
  protected List<Object> areaOrPar;
  @XmlAttribute(name = "ID")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlID
  @XmlSchemaType(name = "ID")
  protected String id;
  @XmlAttribute(name = "ORDER")
  protected BigInteger order;
  @XmlAttribute(name = "ORDERLABEL")
  protected String orderlabel;
  @XmlAttribute(name = "LABEL")
  protected String label;
  @XmlAnyAttribute
  private final Map<QName, String> otherAttributes = new HashMap<>();

  /**
   * Gets the value of the areaOrPar property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a {@code set} method for the areaOrPar property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getAreaOrPar().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link AreaType }
   * {@link ParType }
   *
   * @return The value of the areaOrPar property.
   */
  public List<Object> getAreaOrPar() {
    if (areaOrPar == null) {
      areaOrPar = new ArrayList<>();
    }
    return this.areaOrPar;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getID() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setID(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the order property.
   *
   * @return possible object is
   * {@link BigInteger }
   */
  public BigInteger getORDER() {
    return order;
  }

  /**
   * Sets the value of the order property.
   *
   * @param value allowed object is
   *              {@link BigInteger }
   */
  public void setORDER(BigInteger value) {
    this.order = value;
  }

  /**
   * Gets the value of the orderlabel property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getORDERLABEL() {
    return orderlabel;
  }

  /**
   * Sets the value of the orderlabel property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setORDERLABEL(String value) {
    this.orderlabel = value;
  }

  /**
   * Gets the value of the label property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getLABEL() {
    return label;
  }

  /**
   * Sets the value of the label property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setLABEL(String value) {
    this.label = value;
  }

  /**
   * Gets a map that contains attributes that aren't bound to any typed property on this class.
   *
   * <p>
   * the map is keyed by the name of the attribute and
   * the value is the string value of the attribute.
   * <p>
   * the map returned by this method is live, and you can add new attribute
   * by updating the map directly. Because of this design, there's no setter.
   *
   * @return always non-null
   */
  public Map<QName, String> getOtherAttributes() {
    return otherAttributes;
  }

}
